$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot '..\Modules\InstallerFoundation.ps1')
. (Join-Path $PSScriptRoot '..\Modules\OwnedModFiles.ps1')

$Host.UI.RawUI.WindowTitle='Thief (2014) VR Installer'
$APP_ID='239160';$GAME_EXE='Binaries2\Win64\Shipping-ThiefGame.exe';$REPO='farmerarmor/ThiefVR'
$FALLBACK_TAG='v0.1.0';$FALLBACK_ASSET='ThiefVR-0.1.0-release.zip';$FALLBACK_URL='https://github.com/farmerarmor/ThiefVR/releases/download/v0.1.0/ThiefVR-0.1.0-release.zip'
$IDENTITY='thief2014vr';$RELEASES_URL="https://github.com/$REPO/releases"
$REQUIRED=@('Binaries2\Win64\d3d11.dll','Binaries2\Win64\atidxx64.dll','Binaries2\Win64\atiadlxx.dll','Binaries2\Win64\ThiefVR.ini','Binaries2\Win64\Start Thief VR.bat','Binaries2\Win64\ThiefVR-HubLauncher\launch.ps1','Binaries2\Win64\ThiefVR-HubLauncher\configure-stereo.ps1','Binaries2\Win64\ThiefVR-HubLauncher\dist\ThiefVRLauncher.exe','Binaries2\Win64\ThiefVR-HubLauncher\dist\tools\ThiefVRDisplay.exe','Binaries2\Win64\ThiefVR-backup\install.json')
$contract=New-PCVRInstallerContract -Id 'thief-2014-vr' -GameName 'Thief (2014) VR' -Acquisition GitHub -AntivirusNotice -ReleasePageUrl $RELEASES_URL -RequiredInstalledFileGroups @($REQUIRED+@(".pcvrhub_${IDENTITY}_ownership.csv"))

function Write-ThiefStep([int]$n,[string]$t){Write-Host '';Write-Host "--- [$n/5] $t ---" -ForegroundColor Cyan;Write-Host ''}
function Test-ThiefRoot([string]$p){[bool]($p -and (Test-Path -LiteralPath (Join-Path $p $GAME_EXE) -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $p 'ThiefGame') -PathType Container))}
function Test-ThiefPayload([string]$p){[bool]($p -and (Test-Path -LiteralPath (Join-Path $p 'dist\d3d11.dll') -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $p 'dist\ThiefVRLauncher.exe') -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $p 'configure-stereo.ps1') -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $p 'launch.ps1') -PathType Leaf))}
function Get-ThiefRoot {
    $p=Find-SteamGameFolder -AppId $APP_ID -SteamFolderNames @('Thief') -ProbeExe $GAME_EXE -HubGameId 'thief-2014-vr';if(Test-ThiefRoot $p){return (Get-Item $p).FullName}
    foreach($f in @('C:\Program Files (x86)\Steam\steamapps\common\Thief','C:\Program Files\Steam\steamapps\common\Thief')){if(Test-ThiefRoot $f){return (Get-Item $f).FullName}}
    $p=Get-GameFolderInteractive -GameName 'Thief (2014)' -ProbeFile $GAME_EXE -ManualUrl 'https://github.com/farmerarmor/ThiefVR#installation';if($p -and $p -notin @('quit','skip') -and (Test-ThiefRoot $p)){return (Get-Item $p).FullName};return $null
}
function Get-ThiefRelease {$r=Resolve-GitHubReleaseAsset -Repo $REPO -IncludePrerelease $true -AssetPatterns @('(?i)^ThiefVR-.*release\.zip$') -FallbackUrl $FALLBACK_URL -FallbackTag $FALLBACK_TAG -FallbackAssetName $FALLBACK_ASSET -SkipReleasesWithoutMatchingAsset;[pscustomobject]@{Tag=[string]$r.Tag;Url=[string]$r.Url;Name=[string]$r.AssetName;PageUrl=[string]$r.PageUrl}}
function New-ThiefStage([string]$payload,[string]$stage,[string]$game){
    if(-not(Test-ThiefPayload $payload)){throw 'The publisher archive does not contain the functional ThiefVR launcher and runtime.'}
    $win=Join-Path $stage 'Binaries2\Win64';$hub=Join-Path $win 'ThiefVR-HubLauncher';[void][IO.Directory]::CreateDirectory((Join-Path $hub 'dist\tools'))
    foreach($n in @('d3d11.dll','atidxx64.dll','atiadlxx.dll')){Copy-Item -LiteralPath (Join-Path $payload "dist\$n") -Destination (Join-Path $win $n) -Force};Copy-Item -LiteralPath (Join-Path $payload 'ThiefVR.ini') -Destination (Join-Path $win 'ThiefVR.ini') -Force
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'ThiefVR-HubLaunch.ps1') -Destination (Join-Path $hub 'launch.ps1') -Force;Copy-Item -LiteralPath (Join-Path $payload 'configure-stereo.ps1') -Destination (Join-Path $hub 'configure-stereo.ps1') -Force
    Copy-Item -LiteralPath (Join-Path $payload 'dist\ThiefVRLauncher.exe') -Destination (Join-Path $hub 'dist\ThiefVRLauncher.exe') -Force;Copy-Item -LiteralPath (Join-Path $payload 'dist\tools\ThiefVRDisplay.exe') -Destination (Join-Path $hub 'dist\tools\ThiefVRDisplay.exe') -Force
    $backup=Join-Path $win 'ThiefVR-backup';[void][IO.Directory]::CreateDirectory($backup);$install=[ordered]@{version=1;gameRoot=(Join-Path $game 'Binaries2\Win64');managedBy='PCVR Mods Installer Hub'}|ConvertTo-Json;[IO.File]::WriteAllText((Join-Path $backup 'install.json'),$install,[Text.UTF8Encoding]::new($false))
    $bat='@echo off'+"`r`n"+'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ThiefVR-HubLauncher\launch.ps1" -GameDirectory "%~dp0"'+"`r`n"+'exit /b %errorlevel%'+"`r`n";[IO.File]::WriteAllText((Join-Path $win 'Start Thief VR.bat'),$bat,[Text.Encoding]::ASCII)
    return $stage
}
function Save-ThiefSnapshot([string]$GameRoot,[string]$Stage,[string]$SnapshotRoot){
    $snapshotIdentity='thief2014vr';[void][IO.Directory]::CreateDirectory($SnapshotRoot);$paths=[Collections.Generic.List[string]]::new();$base=[IO.Path]::GetFullPath($Stage).TrimEnd('\','/')
    foreach($file in @(Get-ChildItem -LiteralPath $Stage -File -Recurse -ErrorAction Stop)){$paths.Add($file.FullName.Substring($base.Length+1).Replace('/','\'))}
    $manifest=Join-Path $GameRoot ".pcvrhub_${snapshotIdentity}_ownership.csv";if(Test-Path -LiteralPath $manifest -PathType Leaf){try{foreach($row in @(Import-Csv -LiteralPath $manifest)){if($row.RelativePath){$paths.Add([string]$row.RelativePath)}}}catch{}}
    foreach($extra in @(".pcvrhub_${snapshotIdentity}_ownership.csv",".pcvrhub_${snapshotIdentity}_ownership.csv.new",'.pcvrhub_version')){$paths.Add($extra)}
    $records=@();foreach($relative in @($paths|Select-Object -Unique)){$source=Join-Path $GameRoot $relative;$exists=Test-Path -LiteralPath $source -PathType Leaf;$key=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($relative)).Replace('/','_');$records+=[pscustomobject]@{Relative=$relative;Exists=$exists;Key=$key};if($exists){Copy-Item -LiteralPath $source -Destination (Join-Path $SnapshotRoot $key) -Force -ErrorAction Stop}}
    $backup=Join-Path $GameRoot ".pcvrhub_${snapshotIdentity}_backup";$backupExists=Test-Path -LiteralPath $backup -PathType Container;if($backupExists){Copy-Item -LiteralPath $backup -Destination (Join-Path $SnapshotRoot 'backup') -Recurse -Force -ErrorAction Stop}
    [pscustomobject]@{Records=$records;BackupExists=$backupExists;Root=$SnapshotRoot}
}
function Restore-ThiefSnapshot([string]$GameRoot,$Snapshot){
    foreach($record in @($Snapshot.Records)){$target=Join-Path $GameRoot ([string]$record.Relative);if(Test-Path -LiteralPath $target -PathType Leaf){Remove-Item -LiteralPath $target -Force -ErrorAction SilentlyContinue};if($record.Exists){[void][IO.Directory]::CreateDirectory((Split-Path -Parent $target));Copy-Item -LiteralPath (Join-Path $Snapshot.Root ([string]$record.Key)) -Destination $target -Force -ErrorAction Stop}}
    $backup=Join-Path $GameRoot '.pcvrhub_thief2014vr_backup';if(Test-Path -LiteralPath $backup){Remove-Item -LiteralPath $backup -Recurse -Force -ErrorAction SilentlyContinue};if($Snapshot.BackupExists){Copy-Item -LiteralPath (Join-Path $Snapshot.Root 'backup') -Destination $backup -Recurse -Force -ErrorAction Stop}
}
function global:Invoke-Thief2014VRInstaller {
    $work=$null;$snapshot=$null;$changesStarted=$false
    try{
        Clear-Host;Write-Host ('='*60) -ForegroundColor Magenta;Write-Host '  Thief (2014) VR - Installer' -ForegroundColor Cyan;Write-Host '  Experimental native stereo OpenXR, gamepad or keyboard/mouse' -ForegroundColor Gray;Write-Host ('='*60) -ForegroundColor Magenta;Write-Host ''
        Write-Host '  Requires the 64-bit Steam build 1.7 (4158.21).' -ForegroundColor Yellow;Write-Host '  Quest Link is confirmed. Virtual Desktop needs Center to Stage Tracking.' -ForegroundColor Yellow;Write-Host '  Antivirus software may inspect the runtime; missing files are diagnosed neutrally.' -ForegroundColor Gray;Show-AntivirusNotice -Compact;[void](Wait-PCVRExplicitEnter -Message 'After reading these requirements, press Enter to proceed...')
        Write-ThiefStep 1 'Locating and validating Thief';$game=Get-ThiefRoot;if(-not $game){throw 'Setup was stopped before the game folder was changed.'};if(Get-Process -Name 'Shipping-ThiefGame' -ErrorAction SilentlyContinue){throw 'Thief is running. Close it and retry.'};if(-not(Test-InstallerTargetWritable $game)){throw 'The game folder is not writable. Retry with administrator rights.'}
        if((''+$env:PCVR_THIEFVR_ALLOW_TEST_EXE).Trim() -ne '1'){$hash=(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $game $GAME_EXE)).Hash;if($hash -ne 'BE1BACBB1A6BC67657A91D32C12CE09861CCA57A9FA4AC52BE34BF32A10EA11D'){throw 'This is not the supported Thief 1.7 build 4158.21. Verify the game files or select the supported Steam build.'}}
        Write-Host "  [OK] Found: $game" -ForegroundColor Green
        Write-ThiefStep 2 'Getting the newest prerelease';$release=Get-ThiefRelease;if(-not(Test-IsTrackableInstalledVersion $release.Tag)){throw 'GitHub supplied no trackable ThiefVR version.'};$work=Join-Path ([IO.Path]::GetTempPath()) ('pcvr_thief_'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($work);$zip=Join-Path $work 'ThiefVR.zip';[void](Invoke-SafeDownload -Urls @($release.Url) -Destination $zip -Label "ThiefVR $($release.Tag)" -ManualUrl $release.PageUrl -AllowSkip $false);$extract=Join-Path $work 'extract';[void](Expand-ArchiveOrFallback -ArchivePath $zip -DestinationFolder $extract -Label 'ThiefVR release' -AllowSkip $false -QuietProgress);$payload=Get-ChildItem $extract -Directory -Recurse|Where-Object{Test-ThiefPayload $_.FullName}|Select-Object -First 1 -ExpandProperty FullName;if(-not $payload -and (Test-ThiefPayload $extract)){$payload=$extract};$stage=New-ThiefStage $payload (Join-Path $work 'stage') $game;Write-Host "  [OK] Functional publisher package $($release.Tag) verified." -ForegroundColor Green
        Write-ThiefStep 3 'Preparing the recoverable transaction';Write-Host '  Existing collisions are backed up file by file. ThiefVR.ini is preserved.' -ForegroundColor Gray;$snapshot=Save-ThiefSnapshot -GameRoot $game -Stage $stage -SnapshotRoot (Join-Path $work 'rollback')
        Write-ThiefStep 4 'Installing and checking the VR runtime';$changesStarted=$true;[void](Install-OwnedModPayload -SourceRoot $stage -GameRoot $game -Identity $IDENTITY -KeepExistingRelativePaths @('Binaries2\Win64\ThiefVR.ini') -AdoptIdenticalExisting);$watch=@($REQUIRED|ForEach-Object{Join-Path $game $_})+@(Join-Path $game ".pcvrhub_${IDENTITY}_ownership.csv");if(-not(Confirm-PlacedFilesSurvive -Paths $watch -GameDir $game -NoClear)){throw 'Required ThiefVR files are missing after installation.'};[void](Complete-PCVRInstallTransaction -Contract $contract -GameDir $game -Version $release.Tag -InstalledPathReceiptPaths @((Join-Path $PSScriptRoot '.installed_path')) -Route 'Current');$changesStarted=$false
        Write-ThiefStep 5 'Setup complete';Write-Host '  [OK] ThiefVR is installed, versioned and recoverable.' -ForegroundColor Green;Write-Host '  Always use Start in VR in the Hub; it prepares stereo before launching.' -ForegroundColor White;Write-Host '  [F6] toggles cinema/full VR, [F9] recenters, [F7] corrects the HUD.' -ForegroundColor Cyan;Write-Host '  Use [F6] for keyholes or if looking down leaves the view stuck.' -ForegroundColor Yellow;Write-Host '';Write-Host '  The shadows are safer than the chandeliers. Probably.' -ForegroundColor Magenta;Write-Host '';[void](Wait-PCVRExplicitEnter -Message 'Press Enter to close setup...')
    }catch{if($changesStarted -and $game -and $snapshot){try{Restore-ThiefSnapshot -GameRoot $game -Snapshot $snapshot;Write-Host '  [!!] The previous Thief VR state was restored.' -ForegroundColor Yellow}catch{Write-Host "  [!!] Rollback needs review: $($_.Exception.Message)" -ForegroundColor Yellow}};throw}finally{if($work -and (Test-Path $work)){Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue}}
}
if(((''+$env:PCVR_THIEFVR_LIBRARY_ONLY).Trim()) -ne '1'){Invoke-Thief2014VRInstaller}
