$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot '..\Modules\InstallerFoundation.ps1')
. (Join-Path $PSScriptRoot '..\Modules\OwnedModFiles.ps1')

$Host.UI.RawUI.WindowTitle='Oblivion (2006) VR Installer'
$APP_ID='22330';$GAME_EXE='Oblivion.exe';$REPO='Naragorn/OBVR';$IDENTITY='obvr';$MENU_IDENTITY='obvrmenuque'
$FALLBACK_TAG='v0.2.1';$FALLBACK_ASSET='OBVR-0.2.1.zip';$FALLBACK_URL='https://github.com/Naragorn/OBVR/releases/download/v0.2.1/OBVR-0.2.1.zip'
$XOBSE_REPO='llde/xOBSE';$DXVK_REPO='doitsujin/dxvk';$MENU_URL='https://www.nexusmods.com/oblivion/mods/32200?tab=files'
$XOBSE_FALLBACK_TAG='22.13';$XOBSE_FALLBACK_ASSET='xOBSE-22.13.zip';$XOBSE_FALLBACK_URL='https://github.com/llde/xOBSE/releases/download/22.13/xOBSE-22.13.zip'
$DXVK_FALLBACK_TAG='v3.1.1';$DXVK_FALLBACK_ASSET='dxvk-3.1.1.tar.gz';$DXVK_FALLBACK_URL='https://github.com/doitsujin/dxvk/releases/download/v3.1.1/dxvk-3.1.1.tar.gz'
$REQUIRED=@('obse_loader.exe','obse_1_2_416.dll','obse_steam_loader.dll','d3d9.dll','Data\OBSE\Plugins\OBVR.dll','Data\OBSE\Plugins\OBVR.ini','Data\OBSE\Plugins\openvr_api.dll')
$contract=New-PCVRInstallerContract -Id 'oblivion-2006-vr' -GameName 'Oblivion (2006) VR' -Acquisition GitHub -AntivirusNotice -ReleasePageUrl "https://github.com/$REPO/releases" -RequiredInstalledFileGroups @($REQUIRED+@(".pcvrhub_${IDENTITY}_ownership.csv"))

function Write-OBStep([int]$n,[string]$t){Write-Host '';Write-Host "--- [$n/6] $t ---" -ForegroundColor Cyan;Write-Host ''}
function Test-OBRoot([string]$p){[bool]($p -and (Test-Path (Join-Path $p 'Oblivion.exe') -PathType Leaf) -and (Test-Path (Join-Path $p 'OblivionLauncher.exe') -PathType Leaf) -and (Test-Path (Join-Path $p 'Data\Oblivion.esm') -PathType Leaf))}
function Test-OBPayload([string]$p){[bool]($p -and (Test-Path (Join-Path $p 'OBSE\Plugins\OBVR.dll') -PathType Leaf) -and (Test-Path (Join-Path $p 'OBSE\Plugins\OBVR.ini') -PathType Leaf))}
function Test-MenuQuePayload([string]$p){[bool]($p -and (Test-Path (Join-Path $p 'Data\OBSE\Plugins\MenuQue.dll') -PathType Leaf))}
function Get-OBRoot {
    $p=Find-SteamGameFolder -AppId $APP_ID -SteamFolderNames @('Oblivion') -ProbeExe $GAME_EXE -HubGameId 'oblivion-2006-vr';if(Test-OBRoot $p){return (Get-Item $p).FullName}
    foreach($f in @('C:\Program Files (x86)\Steam\steamapps\common\Oblivion','C:\Program Files (x86)\GOG Galaxy\Games\Oblivion','C:\GOG Games\Oblivion','C:\Program Files (x86)\Bethesda Softworks\Oblivion')){if(Test-OBRoot $f){return (Get-Item $f).FullName}}
    $p=Get-GameFolderInteractive -GameName 'The Elder Scrolls IV: Oblivion (2006)' -ProbeFile 'Oblivion.exe' -ManualUrl 'https://github.com/Naragorn/OBVR#installation';if($p -and $p -notin @('quit','skip') -and (Test-OBRoot $p)){return (Get-Item $p).FullName};return $null
}
function Get-OBRelease([string]$repo,[string[]]$patterns,[switch]$Prerelease,[string]$fallbackUrl='',[string]$fallbackTag='',[string]$fallbackName=''){$resolveArgs=@{Repo=$repo;AssetPatterns=$patterns;SkipReleasesWithoutMatchingAsset=$true};if($Prerelease){$resolveArgs.IncludePrerelease=$true};if($fallbackUrl){$resolveArgs.FallbackUrl=$fallbackUrl;$resolveArgs.FallbackTag=$fallbackTag;$resolveArgs.FallbackAssetName=$fallbackName};$r=Resolve-GitHubReleaseAsset @resolveArgs;[pscustomobject]@{Tag=[string]$r.Tag;Url=[string]$r.Url;Name=[string]$r.AssetName;PageUrl=[string]$r.PageUrl}}
function Find-OBPayloadRoot([string]$root){if(Test-OBPayload $root){return $root};Get-ChildItem $root -Directory -Recurse|Where-Object{Test-OBPayload $_.FullName}|Select-Object -First 1 -ExpandProperty FullName}
function Find-XOBSERoot([string]$root){if(Test-Path (Join-Path $root 'obse_loader.exe')){return $root};Get-ChildItem $root -Directory -Recurse|Where-Object{Test-Path (Join-Path $_.FullName 'obse_loader.exe')}|Select-Object -First 1 -ExpandProperty FullName}
function Find-DXVK32([string]$root){Get-ChildItem $root -Filter d3d9.dll -File -Recurse|Where-Object{$_.FullName -match '[\\/]x32[\\/]'}|Select-Object -First 1 -ExpandProperty FullName}
function Test-X86Dll([string]$path){if(-not(Test-Path $path)){return $false};$fs=[IO.File]::OpenRead($path);try{$br=[IO.BinaryReader]::new($fs);if($br.ReadUInt16() -ne 0x5A4D){return $false};$fs.Position=0x3c;$pe=$br.ReadInt32();$fs.Position=$pe;if($br.ReadUInt32() -ne 0x4550){return $false};return ($br.ReadUInt16() -eq 0x14c)}finally{$fs.Dispose()}}
function Get-OpenVR32 {
    $p=Find-SteamGameFolder -AppId '250820' -SteamFolderNames @('SteamVR') -ProbeExe 'bin\win32\openvr_api.dll' -HubGameId '';if($p){$dll=Join-Path $p 'bin\win32\openvr_api.dll';if(Test-X86Dll $dll){return $dll}}
    foreach($dll in @('C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\openvr_api.dll','C:\Program Files\Steam\steamapps\common\SteamVR\bin\win32\openvr_api.dll')){if(Test-X86Dll $dll){return $dll}}
    while($true){Write-Host '  SteamVR 32-bit openvr_api.dll was not found.' -ForegroundColor Yellow;Write-Host '  [S] Open SteamVR installation page   [D] Drag/drop or paste DLL   [R] Retry scan' -ForegroundColor White;$c=([string](Read-Host 'Choice')).Trim().ToUpperInvariant();if($c -eq 'S'){[void](Wait-PCVRExplicitEnter -Message 'Press Enter to open SteamVR in Steam...');Start-Process 'steam://install/250820';continue};if($c -eq 'D'){$x=([string](Read-Host 'Drop or paste openvr_api.dll')).Trim().Trim('"');if(Test-X86Dll $x){return (Get-Item $x).FullName};Write-Host '  That is not a usable 32-bit openvr_api.dll.' -ForegroundColor Yellow;continue};if($c -eq 'R'){return (Get-OpenVR32)}}
}
function Get-MenuQueArchive([string]$work){
    if(Test-Path (Join-Path $script:OBGame 'Data\OBSE\Plugins\MenuQue.dll')){return $null}
    Write-Host '  MenuQue v16b is required for OBVR onboarding and native menus.' -ForegroundColor Yellow;[void](Wait-PCVRExplicitEnter -Message 'Press Enter to open the official Nexus Files page...');Start-Process $MENU_URL;[void](Wait-PCVRExplicitEnter -Message 'After downloading MenuQue v16b, press Enter to search Downloads...')
    $downloads=[Environment]::GetFolderPath('UserProfile')+'\Downloads';$candidate=Get-ChildItem $downloads -File -ErrorAction SilentlyContinue|Where-Object{$_.Name -match '(?i)menuque.*(zip|7z|rar)$'}|Sort-Object LastWriteTime -Descending|Select-Object -First 1
    while(-not $candidate){Write-Host '  MenuQue was not found. Drag/drop its archive, reopen Nexus, or search again.' -ForegroundColor Yellow;Write-Host '  [D] Drag/drop path   [N] Open Nexus   [R] Search Downloads' -ForegroundColor White;$c=([string](Read-Host 'Choice')).Trim().ToUpperInvariant();if($c -eq 'N'){Start-Process $MENU_URL;continue};if($c -eq 'D'){$p=([string](Read-Host 'Archive')).Trim().Trim('"');if(Test-Path $p -PathType Leaf){$candidate=Get-Item $p}}elseif($c -eq 'R'){$candidate=Get-ChildItem $downloads -File -ErrorAction SilentlyContinue|Where-Object{$_.Name -match '(?i)menuque.*(zip|7z|rar)$'}|Sort-Object LastWriteTime -Descending|Select-Object -First 1}}
    return $candidate.FullName
}
function New-OBStage([string]$ob,[string]$xobse,[string]$dxvk,[string]$openvr,[string]$stage){
    $xo=Find-XOBSERoot $xobse;$d9=Find-DXVK32 $dxvk;if(-not $xo -or -not $d9 -or -not(Test-OBPayload $ob) -or -not(Test-X86Dll $openvr)){throw 'One of the four functional runtime inputs could not be normalized.'};[void][IO.Directory]::CreateDirectory($stage)
    foreach($n in @('obse_loader.exe','obse_1_2_416.dll','obse_editor_1_2.dll','obse_steam_loader.dll')){if(Test-Path (Join-Path $xo $n)){Copy-Item (Join-Path $xo $n) (Join-Path $stage $n) -Force}}
    if(Test-Path (Join-Path $xo 'Data')){Copy-Item (Join-Path $xo 'Data') $stage -Recurse -Force};Copy-Item $d9 (Join-Path $stage 'd3d9.dll') -Force;[void][IO.Directory]::CreateDirectory((Join-Path $stage 'Data\OBSE\Plugins'));Copy-Item (Join-Path $ob 'OBSE') (Join-Path $stage 'Data') -Recurse -Force;if(Test-Path (Join-Path $ob 'Menus')){Copy-Item (Join-Path $ob 'Menus') (Join-Path $stage 'Data') -Recurse -Force};Copy-Item $openvr (Join-Path $stage 'Data\OBSE\Plugins\openvr_api.dll') -Force;return $stage
}
function Save-OBSnapshot([string]$GameRoot,[string]$Stage,[string]$SnapshotRoot,[string]$Identity){
    [void][IO.Directory]::CreateDirectory($SnapshotRoot);$paths=[Collections.Generic.List[string]]::new();$base=[IO.Path]::GetFullPath($Stage).TrimEnd('\','/')
    foreach($file in @(Get-ChildItem -LiteralPath $Stage -File -Recurse -ErrorAction Stop)){$paths.Add($file.FullName.Substring($base.Length+1).Replace('/','\'))};$manifest=Join-Path $GameRoot ".pcvrhub_${Identity}_ownership.csv";if(Test-Path -LiteralPath $manifest -PathType Leaf){try{foreach($row in @(Import-Csv -LiteralPath $manifest)){if($row.RelativePath){$paths.Add([string]$row.RelativePath)}}}catch{}}
    foreach($extra in @(".pcvrhub_${Identity}_ownership.csv",".pcvrhub_${Identity}_ownership.csv.new",'.pcvrhub_version')){$paths.Add($extra)};$records=@();foreach($relative in @($paths|Select-Object -Unique)){$source=Join-Path $GameRoot $relative;$exists=Test-Path -LiteralPath $source -PathType Leaf;$key=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($relative)).Replace('/','_');$records+=[pscustomobject]@{Relative=$relative;Exists=$exists;Key=$key};if($exists){Copy-Item -LiteralPath $source -Destination (Join-Path $SnapshotRoot $key) -Force -ErrorAction Stop}}
    $backup=Join-Path $GameRoot ".pcvrhub_${Identity}_backup";$backupExists=Test-Path -LiteralPath $backup -PathType Container;if($backupExists){Copy-Item -LiteralPath $backup -Destination (Join-Path $SnapshotRoot 'backup') -Recurse -Force -ErrorAction Stop};[pscustomobject]@{Records=$records;BackupExists=$backupExists;Root=$SnapshotRoot;Identity=$Identity}
}
function Restore-OBSnapshot([string]$GameRoot,$Snapshot){foreach($record in @($Snapshot.Records)){$target=Join-Path $GameRoot ([string]$record.Relative);if(Test-Path -LiteralPath $target -PathType Leaf){Remove-Item -LiteralPath $target -Force -ErrorAction SilentlyContinue};if($record.Exists){[void][IO.Directory]::CreateDirectory((Split-Path -Parent $target));Copy-Item -LiteralPath (Join-Path $Snapshot.Root ([string]$record.Key)) -Destination $target -Force -ErrorAction Stop}};$backup=Join-Path $GameRoot ".pcvrhub_$($Snapshot.Identity)_backup";if(Test-Path -LiteralPath $backup){Remove-Item -LiteralPath $backup -Recurse -Force -ErrorAction SilentlyContinue};if($Snapshot.BackupExists){Copy-Item -LiteralPath (Join-Path $Snapshot.Root 'backup') -Destination $backup -Recurse -Force -ErrorAction Stop}}
function global:Invoke-Oblivion2006VRInstaller {
    $work=$null;$mainSnapshot=$null;$menuSnapshot=$null;$mainChanged=$false;$menuChanged=$false
    try{
        Clear-Host;Write-Host ('='*60) -ForegroundColor Magenta;Write-Host '  Oblivion (2006) VR - Installer' -ForegroundColor Cyan;Write-Host '  Experimental native stereo, gamepad or keyboard/mouse' -ForegroundColor Gray;Write-Host ('='*60) -ForegroundColor Magenta;Write-Host ''
        Write-Host '  This is for the original 2006 game, version 1.2.0.416.' -ForegroundColor Yellow;Write-Host '  Steam is tested; GOG and retail are currently untested.' -ForegroundColor Yellow;Write-Host '  Motion controls exist in development but are disabled in this release.' -ForegroundColor Yellow;Show-AntivirusNotice -Compact;[void](Wait-PCVRExplicitEnter -Message 'After reading these requirements, press Enter to proceed...')
        Write-OBStep 1 'Locating Oblivion';$script:OBGame=Get-OBRoot;if(-not $script:OBGame){throw 'Setup was stopped before changing the game.'};if(Get-Process -Name 'Oblivion','obse_loader' -ErrorAction SilentlyContinue){throw 'Oblivion is running. Close it and retry.'};if(-not(Test-InstallerTargetWritable $script:OBGame)){throw 'The game folder is not writable.'};Write-Host "  [OK] Found: $script:OBGame" -ForegroundColor Green
        Write-OBStep 2 'Getting OBVR, xOBSE and DXVK';$work=Join-Path ([IO.Path]::GetTempPath()) ('pcvr_obvr_'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($work);$obRel=Get-OBRelease $REPO @('(?i)^OBVR-.*\.zip$') -fallbackUrl $FALLBACK_URL -fallbackTag $FALLBACK_TAG -fallbackName $FALLBACK_ASSET;$xoRel=Get-OBRelease $XOBSE_REPO @('(?i)^xOBSE-.*\.zip$') -fallbackUrl $XOBSE_FALLBACK_URL -fallbackTag $XOBSE_FALLBACK_TAG -fallbackName $XOBSE_FALLBACK_ASSET;$dxRel=Get-OBRelease $DXVK_REPO @('(?i)^dxvk-.*\.tar\.gz$') -fallbackUrl $DXVK_FALLBACK_URL -fallbackTag $DXVK_FALLBACK_TAG -fallbackName $DXVK_FALLBACK_ASSET;foreach($r in @($obRel,$xoRel,$dxRel)){if(-not(Test-IsTrackableInstalledVersion $r.Tag)){throw 'A dependency supplied no trackable release version.'}}
        $i=0;$roots=@();foreach($pair in @(@($obRel,'obvr.zip'),@($xoRel,'xobse.zip'),@($dxRel,'dxvk.tar.gz'))){$i++;$arc=Join-Path $work $pair[1];[void](Invoke-SafeDownload -Urls @($pair[0].Url) -Destination $arc -Label $pair[0].Name -ManualUrl $pair[0].PageUrl -AllowSkip $false);$out=Join-Path $work "extract$i";[void](Expand-ArchiveOrFallback -ArchivePath $arc -DestinationFolder $out -Label $pair[0].Name -AllowSkip $false -QuietProgress);if($pair[1] -like '*.tar.gz'){$tar=Get-ChildItem $out -Filter *.tar -File -Recurse|Select-Object -First 1;if($tar){$out2=Join-Path $work 'extract-dxvk-tar';[void](Expand-ArchiveOrFallback -ArchivePath $tar.FullName -DestinationFolder $out2 -Label 'DXVK tar payload' -AllowSkip $false -QuietProgress);$out=$out2}};$roots+=$out}
        $obRoot=Find-OBPayloadRoot $roots[0];$openvr=Get-OpenVR32;$stage=New-OBStage $obRoot $roots[1] $roots[2] $openvr (Join-Path $work 'stage');$mainSnapshot=Save-OBSnapshot -GameRoot $script:OBGame -Stage $stage -SnapshotRoot (Join-Path $work 'rollback-main') -Identity $IDENTITY;Write-Host "  [OK] OBVR $($obRel.Tag), xOBSE $($xoRel.Tag) and DXVK $($dxRel.Tag) verified." -ForegroundColor Green
        Write-OBStep 3 'Installing MenuQue v16b when needed';$menu=Get-MenuQueArchive $work;if($menu){$mext=Join-Path $work 'menuque';[void](Expand-ArchiveOrFallback -ArchivePath $menu -DestinationFolder $mext -Label 'MenuQue v16b' -AllowSkip $false -QuietProgress);$mroot=if(Test-MenuQuePayload $mext){$mext}else{Get-ChildItem $mext -Directory -Recurse|Where-Object{Test-MenuQuePayload $_.FullName}|Select-Object -First 1 -ExpandProperty FullName};if(-not $mroot){throw 'The selected archive does not contain Data\OBSE\Plugins\MenuQue.dll.'};$menuSnapshot=Save-OBSnapshot -GameRoot $script:OBGame -Stage $mroot -SnapshotRoot (Join-Path $work 'rollback-menuque') -Identity $MENU_IDENTITY;$menuChanged=$true;[void](Install-OwnedModPayload -SourceRoot $mroot -GameRoot $script:OBGame -Identity $MENU_IDENTITY -AdoptIdenticalExisting);Write-Host '  [OK] MenuQue installed as a separately owned shared dependency.' -ForegroundColor Green}else{Write-Host '  [OK] Existing MenuQue installation retained.' -ForegroundColor Green}
        Write-OBStep 4 'Preparing the recoverable VR transaction';Write-Host '  Existing collisions are backed up file by file. OBVR.ini is preserved.' -ForegroundColor Gray
        Write-OBStep 5 'Installing and checking OBVR';$mainChanged=$true;[void](Install-OwnedModPayload -SourceRoot $stage -GameRoot $script:OBGame -Identity $IDENTITY -KeepExistingRelativePaths @('Data\OBSE\Plugins\OBVR.ini') -AdoptIdenticalExisting);$watch=@($REQUIRED|ForEach-Object{Join-Path $script:OBGame $_})+@(Join-Path $script:OBGame ".pcvrhub_${IDENTITY}_ownership.csv");if(-not(Confirm-PlacedFilesSurvive -Paths $watch -GameDir $script:OBGame -NoClear)){throw 'Required OBVR runtime files are missing after installation.'};[void](Complete-PCVRInstallTransaction -Contract $contract -GameDir $script:OBGame -Version $obRel.Tag -InstalledPathReceiptPaths @((Join-Path $PSScriptRoot '.installed_path')) -Route 'Current');$mainChanged=$false;$menuChanged=$false
        Write-OBStep 6 'Setup complete';Write-Host '  [OK] OBVR is installed, versioned and recoverable.' -ForegroundColor Green;Write-Host '  Disable Steam Overlay, then use Start in VR in the Hub.' -ForegroundColor White;Write-Host '  Start in VR starts SteamVR first and then uses obse_loader.exe.' -ForegroundColor White;Write-Host '  OBVR uses OpenVR; VDXR is not an alternative runtime for this mod.' -ForegroundColor Yellow;Write-Host '  [Insert] opens VR settings and [Delete] recenters.' -ForegroundColor Cyan;Write-Host '';Write-Host '  The gates of Oblivion were never designed around a headset cable.' -ForegroundColor Magenta;Write-Host '';[void](Wait-PCVRExplicitEnter -Message 'Press Enter to close setup...')
    }catch{if($mainChanged -and $script:OBGame -and $mainSnapshot){try{Restore-OBSnapshot -GameRoot $script:OBGame -Snapshot $mainSnapshot}catch{Write-Host "  [!!] OBVR rollback needs review: $($_.Exception.Message)" -ForegroundColor Yellow}};if($menuChanged -and $script:OBGame -and $menuSnapshot){try{Restore-OBSnapshot -GameRoot $script:OBGame -Snapshot $menuSnapshot}catch{Write-Host "  [!!] MenuQue rollback needs review: $($_.Exception.Message)" -ForegroundColor Yellow}};if($mainChanged -or $menuChanged){Write-Host '  [!!] The previous Oblivion VR state was restored.' -ForegroundColor Yellow};throw}finally{Remove-Variable OBGame -Scope Script -ErrorAction SilentlyContinue;if($work -and (Test-Path $work)){Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue}}
}
if(((''+$env:PCVR_OBVR_LIBRARY_ONLY).Trim()) -ne '1'){Invoke-Oblivion2006VRInstaller}
